In [3]:
import numpy as np;
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [13]:
import numpy as np

new_arr=[[[1,2,3],[3,4,5],[5,6,7],[7,8,9]]]
print(new_arr[1:1:1])


[]
