In [9]:
'''Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
 Product (prod)
 Multiplication (multiply)
 Dot Product (dot)'''
import numpy as np

matrix1 = np.array([[float(input("Enter value for matrix1[{}][{}]: ".format(i, j))) for j in range(3)] for i in range(3)])
matrix2 = np.array([[float(input("Enter value for matrix2[{}][{}]: ".format(i, j))) for j in range(3)] for i in range(3)])

# Perform product operation
product = np.prod([matrix1, matrix2], axis=0)

# Perform multiplication operation
multiplication = np.multiply(matrix1, matrix2)

# Perform dot product operation
dot_product = np.dot(matrix1, matrix2)

# Print the matrices and the results of the operations
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Product:\n", product)
print("Multiplication:\n", multiplication)
print("Dot Product:\n", dot_product)

Matrix 1:
 [[1. 2. 3.]
 [4. 1. 2.]
 [3. 4. 1.]]
Matrix 2:
 [[2. 5. 6.]
 [7. 3. 4.]
 [5. 2. 3.]]
Product:
 [[ 2. 10. 18.]
 [28.  3.  8.]
 [15.  8.  3.]]
Multiplication:
 [[ 2. 10. 18.]
 [28.  3.  8.]
 [15.  8.  3.]]
Dot Product:
 [[31. 17. 23.]
 [25. 27. 34.]
 [39. 29. 37.]]


In [2]:
'''Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR
'''
import numpy as np

# Create two NumPy arrays to represent sets
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7])

print(set1)
print(set2)

# Union
union_result = np.union1d(set1, set2)
print("Union Result:")
print(union_result)

# Intersection
intersection_result = np.intersect1d(set1, set2)
print("Intersection Result:")
print(intersection_result)

# Set Difference (set1 - set2)
set_difference_result = np.setdiff1d(set1, set2)
print("Set Difference Result (set1 - set2):")
print(set_difference_result)

# XOR (Symmetric Difference)
xor_result = np.setxor1d(set1, set2)
print("XOR (Symmetric Difference) Result:")
print(xor_result)

[1 2 3 4 5]
[3 4 5 6 7]
Union Result:
[1 2 3 4 5 6 7]
Intersection Result:
[3 4 5]
Set Difference Result (set1 - set2):
[1 2]
XOR (Symmetric Difference) Result:
[1 2 6 7]


In [17]:
'''Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array'''

import numpy as np

array = np.random.randint(10, size=10)

print("Array:")
print(array)

# Calculate the cumulative sum of the array
cumulative_sum = np.cumsum(array)

# Print the cumulative sum
print("\nCumulative sum:")
print(cumulative_sum)

# Calculate the cumulative product of the array
cumulative_product = np.cumprod(array)

# Print the cumulative product
print("\nCumulative product:")
print(cumulative_product)

# Calculate the discrete difference of the array with n=3
discrete_difference = np.diff(array, n=3)

# Print the discrete difference
print("\nDiscrete difference (n=3):")
print(discrete_difference)

# Find the unique elements from the array
unique_elements = np.unique(array)

print("\nUnique elements:")
print(unique_elements)

Array:
[7 6 8 6 0 7 0 6 9 1]

Cumulative sum:
[ 7 13 21 27 27 34 34 40 49 50]

Cumulative product:
[   7   42  336 2016    0    0    0    0    0    0]

Discrete difference (n=3):
[ -7   0  17 -27  27 -16  -8]

Unique elements:
[0 1 6 7 8 9]


In [15]:
'''Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())'''
import numpy as np

# Create two 1D arrays
array1 = np.array([10,5,15,20,25])
array2 = np.array([1,3,5,7,9])

# Perform addition using zip()
addition_zip = [x + y for x, y in zip(array1, array2)]
print("Addition using zip():")
print(addition_zip)

# Perform addition using numpy.add()
addition_np = np.add(array1, array2)
print("Addition using numpy.add():")
print(addition_np)

# Define a user-defined addition function using numpy.frompyfunc()
def custom_add(x, y):
    return x + y

addition_custom = np.frompyfunc(custom_add, 2, 1)(array1, array2)
print("Addition using user-defined function (frompyfunc()):")
print(addition_custom)

Addition using zip():
[11, 8, 20, 27, 34]
Addition using numpy.add():
[11  8 20 27 34]
Addition using user-defined function (frompyfunc()):
[11 8 20 27 34]


In [14]:
'''Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().'''

from functools import reduce
import math

# Define a function to find the LCM of two numbers
def lcm(x, y):
    return x * y // math.gcd(x, y)

# Define a function to find the GCD of two numbers
def gcd(x, y):
    return math.gcd(x, y)

# Example array of elements
array = [11,23,30,6]

# Find the LCM of the elements in the array
lcm_result = reduce(lcm, array)

# Find the GCD of the elements in the array
gcd_result = reduce(gcd, array)

print("Array:", array)
print("LCM of the elements:", lcm_result)
print("GCD of the elements:", gcd_result)

Array: [11, 23, 30, 6]
LCM of the elements: 7590
GCD of the elements: 1
